"""add_video_and_donor_message_fields

Revision ID: 5ecbdf998c32
Revises: 001
Create Date: 2026-07-21 00:37:33.123057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ecbdf998c32'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_anonymous', sa.Boolean(), nullable=True))

    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('media_consent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_column('media_consent')
        batch_op.drop_column('video_url')

    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.drop_column('is_anonymous')
        batch_op.drop_column('message')

    # ### end Alembic commands ###
